<?xml version="1.0" encoding="utf-8"?><Database Name="Curse" Class="SportsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=Curse;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CurseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AvatarName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RBI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HomeRun" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Average" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Team_Player" Member="Team" ThisKey="TeamId" OtherKey="ID" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AvatarName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Team_Player" Member="Players" ThisKey="ID" OtherKey="TeamId" Type="Player" />
    </Type>
  </Table>
</Database>